Remove use of size_t in Rust code
Needed to upgrade bindgen from 0.59.0 to 0.63.0. Resolves the
following errors:

//#[path = "../../../src/options.rs"]
//mod options;

error[E0432]: unresolved import `keystore2_apc_compat_bindgen::size_t`
  --> system/security/keystore2/apc_compat/apc_compat.rs:22:82
   |
22 |     abortUserConfirmation, closeUserConfirmationService, promptUserConfirmation, size_t,
   |
      ^^^^^^ no `size_t` in the root

error[E0412]: cannot find type `size_t` in this scope
  --> system/security/keystore2/apc_compat/apc_compat.rs:79:23
   |
79 |     tbs_message_size: size_t,
   |                       ^^^^^^ not found in this scope

error[E0412]: cannot find type `size_t` in this scope
  --> system/security/keystore2/apc_compat/apc_compat.rs:81:30
   |
81 |     confirmation_token_size: size_t,
   |                              ^^^^^^ not found in this scope

error[E0412]: cannot find type `size_t` in this scope
   --> system/security/keystore2/apc_compat/apc_compat.rs:181:37
    |
181 |                 extra_data.len() as size_t,
    |                                     ^^^^^^ not found in this scope

Test: Treehugger
Change-Id: I848f481627f3c14caa6252eee6b5dd40d2f58eed